# Generated by Django 5.2.4 on 2025-07-16 07:28

import bitemporal.db_backend.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clean", "0001_initial"),
    ]

    operations = [
        bitemporal.db_backend.migrations.SystemVersioning(
            model_name="company",
            add=True,
        ),
    ]
